Add RelationshipEncapsulationTests
usd-wg/assets pull request #66
Opened 2023-11-17 15:44 UTC by mati-nvidia

As shown at the working group meeting, yhese are tests demonstrating unencapsulated relationships for references.

2023-11-24 19:16 UTC, meshula commented
Very nicely presented!

2023-11-24 19:17 UTC, meshula approved these changes

2023-11-28 16:29 UTC, jcowles requested changes
Would you mind adding license info to the readme?

Here is an example (see the bottom of the readme):
https://github.com/mati-nvidia/assets/tree/main/test_assets/NormalsTextureBiasAndScale

2023-11-29 16:10 UTC, jcowles commented
w00t, thanks - merging!

2023-11-29 16:10 UTC, jcowles approved these changes

2023-11-29 16:11 UTC, merged